# 서버포트 번호
server:
  port: 8080

  tomcat:
    max-http-form-post-size: 10GB


spring:
  application:
    name: QuickBeat-v2

  thymeleaf:
    cache: false
    prefix: classpath:templates/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quickbeat_v2_db?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  # security
  security:
    user:
      name: user
      password: 12345678

      # oauth2 client
    oauth2:
      client:
        registration:

          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

# MyBatis 매퍼(mapper) 파일 위치 설정
# src/main/resources 이하의 경로 지정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:

  oauth2:
    #공통 비번
    password: 12345678